# Generated by Django 5.1.6 on 2025-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
