# Generated by Django 5.1.6 on 2025-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
