# Generated by Django 5.1.6 on 2025-05-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userproducts',
            old_name='user_id',
            new_name='user',
        ),
    ]
