# Generated by Django 5.1.6 on 2025-05-15 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_product_id_userproducts_product_and_more'),
        ('store', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='store.products'),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='accounts.users'),
        ),
    ]
