# Generated by Django 5.1.6 on 2025-05-29 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userproducts_product_alter_userproducts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproducts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 19, 16, 42, 426184)),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='status',
            field=models.CharField(default='В процессе приобретения', max_length=50),
        ),
    ]
