# Generated by Django 5.1.6 on 2025-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userproducts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
