# Generated by Django 5.1.6 on 2025-05-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Сооружение', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prepaid', models.BooleanField(default=False)),
                ('addres', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('mortgage', models.BooleanField(default=False)),
                ('tier', models.CharField(max_length=50)),
                ('room_count', models.IntegerField(max_length=100)),
                ('size', models.IntegerField(max_length=30)),
                ('facing', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
            ],
        ),
    ]
