# Generated by Django 5.1.6 on 2025-05-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='room_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='year',
            field=models.IntegerField(),
        ),
    ]
