# Generated by Django 5.1.6 on 2025-05-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_room_count_alter_products_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='addres',
            new_name='address',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(default='unknown', upload_to='products/'),
            preserve_default=False,
        ),
    ]
