# Generated by Django 5.1.6 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_addres_products_address_products_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='unknow', max_length=2300),
            preserve_default=False,
        ),
    ]
