# Generated by Django 5.1.6 on 2025-05-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='Нет описания', max_length=2300),
        ),
    ]
