# Generated by Django 5.1.6 on 2025-05-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userproducts_product_alter_userproducts_user'),
        ('payments', '0002_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='title',
            field=models.CharField(default='Платеж', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='accounts.users'),
        ),
    ]
