# Generated by Django 5.1.6 on 2025-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments_title_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('refunded', 'Возврат'), ('canceled', 'Отменено'), ('in_progress', 'В процессе')], default='pending', max_length=20),
        ),
    ]
