# Generated by Django 5.1.6 on 2025-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
